left to right direction

interface ICustomerID {
    + object Value { get; }
}

interface ITaxCode {
    + string Code { get; }
}

interface IVatNumber {
    + uint Number { get; }
}

interface ICustomer {
    + ICustomerID Id { get; }
    + string Name { get; **set;** }
    + string Email { get; **set;** }
}

ICustomer "1" *-- "1" ICustomerID

IVatNumber --|> ICustomerID
ITaxCode --|> ICustomerID

interface ICustomerFactory {
    + ITaxCode ComputeTaxCode(string name, string surname, DateTime birthDate, string birthPlace)
    --
    + ICustomer NewCustomerPerson(ITaxCode code, string fullName, string email)
    + ICustomer NewCustomerPerson(string name, string surname, DateTime birthDate, string birthPlace, string email)
    --
    + ICustomer NewCustomerCompany(IVatNumber code, string fullName, string email)
}

ICustomerFactory --> IVatNumber: creates
ICustomerFactory --> ICustomer: creates