left to right direction

interface ICustomerID 

interface ICustomer

ICustomer "1" *-- "1" ICustomerID

interface ICustomerRegistry {
    + IEnumerable<ICustomer> AllCustomers { get; }
    --
    + ICustomer FindCustomerById(ICustomerID id);
    + IEnumerable<ICustomer> FindCustomerByName(string name);
    + IEnumerable<ICustomer> FindCustomerByEmail(string email);
    ..
    + void AddNewCustomer(ICustomer customer);
    + void UpdateCustomer(ICustomer customer);
    + void RemoveCustomer(ICustomer customer);
}

ICustomerRegistry "1" o--> "N" ICustomer: contains
ICustomerRegistry --> ICustomerID: exploits